// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ln_dcmp
NumericVector ln_dcmp(const NumericVector& x, const NumericVector& mu, const NumericVector& nu);
RcppExport SEXP cmpR_ln_dcmp(SEXP xSEXP, SEXP muSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(ln_dcmp(x, mu, nu));
    return rcpp_result_gen;
END_RCPP
}
// samp_cmp
IntegerVector samp_cmp(const int& n, const double& mu, const double& nu);
RcppExport SEXP cmpR_samp_cmp(SEXP nSEXP, SEXP muSEXP, SEXP nuSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const double& >::type nu(nuSEXP);
    rcpp_result_gen = Rcpp::wrap(samp_cmp(n, mu, nu));
    return rcpp_result_gen;
END_RCPP
}
