# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ln_dcmp <- function(x, mu, nu) {
    .Call('cmpR_ln_dcmp', PACKAGE = 'cmpR', x, mu, nu)
}

samp_cmp <- function(n, mu, nu) {
    .Call('cmpR_samp_cmp', PACKAGE = 'cmpR', n, mu, nu)
}

